name: v2ray

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/v2ray_ws/*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build the v2ray_ws Docker image and push to the docker hub
        uses: docker/build-push-action@v2
        with:
          context: docker/v2ray_ws/
          file: docker/v2ray_ws/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/v2ray:ws
